# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target ’GroceryStore’ do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for Grocery Store

pod 'AFNetworking', '~> 3.0'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'IQKeyboardManager'

pod 'Firebase/Messaging'
pod 'Firebase/Firestore'

pod 'Firebase'
pod 'Firebase/Auth'

pod 'Firebase/Core'
pod 'FirebaseUI/Phone'
pod 'FirebaseUI/Auth'

pod 'JTCalendar'


pod 'SVProgressHUD'



end
